services:
  postgres:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
         - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL",  pg_isready -U $$POSTGRES_USER" ]
      interval: 30s
      timeout: 10s
      retries: 5
  api:
    image: "rest_api"
    ports:
      - 8080:8080
    depends_on:
      - postgres
    links:
      - postgres
    healthcheck:
        test: ["CMD", "curl", "-d", "'{\"field1\":\"test3333\", \"field2\":\"test3333\"}' -H \"content-type: application/json\" -X POST 192.168.50.76:8080/postData"]
        interval: 10s
        timeout: 5s
        retries: 5


