services:
  postgres:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
        - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    image: "rest_api"
    ports:
      - 8080:8080
    depends_on:
      - postgres
    links:
      - postgres